services:
  app:
    image: sybercat/express-app:latest
    container_name: express-app
    ports:
      - "8080:8080"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup express-app
    restart: unless-stopped