services:
  app:
    image: sybercat/express-app:latest
    container_name: express-app
    ports:
      - "8080:8080"
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower